version: '3.8'

services:
  webapp:
    image: 'webapp'
    build: . 
    volumes:
      -.:/webapp
    ports:
      - 9000:9000
    environment:
      - port = 9000
    command: npm run start

volumes:
node_modules: